apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: jupyter
  description: This is an application that promotes inclusion through a web portal
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./groups/org.yaml
    - ./components/service/component.yaml
    - ./systems/system.yaml
    - ./domains/domain.yaml
